//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleMonitor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockedIp
    {
        public int Id { get; set; }
        public string IpAddress { get; set; }
        public bool IsBlocked { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public int BlockHit { get; set; }
    }
}
